Sigma, Pi and Identity Types structure over cwf
UniMath/TypeTheory pull request #189
Opened 2021-05-28 21:03 UTC by tvignon

This PR formalize : 

- Sigma Type over a category with family
- Pi Type over a category with family
- Identity Type over a category with family (still a work in progress)
- Family of Types over a category with family

This use a version of term with the internal typing directly taken into account.

2021-05-29 17:18 UTC, benediktahrens requested changes

2021-05-29 17:18 UTC, benediktahrens commented on TypeTheory/TypeConstructions/CwF_Structure_Display.v
> +Definition id_right (E : category) := pr2121 E.
Aren't these definitions there already? Maybe even under the exact same name?

2021-05-29 17:18 UTC, benediktahrens commented on TypeTheory/TypeConstructions/CwF_Structure_Display.v
> +Qed.
Is it possible to use an existing lemma instead of this one?

2021-05-29 17:18 UTC, benediktahrens commented on TypeTheory/TypeConstructions/CwF_Structure_Display.v
> +:= pr12 p Γ.
What is the type of this definition?

2021-05-29 17:18 UTC, benediktahrens commented on TypeTheory/TypeConstructions/CwF_Structure_Display.v
> +Definition CwF_Pullback {Γ} (A : Ty Γ : hSet) := pr22 pr22 CwF Γ A.
Please add a type annotation.

2021-05-29 17:18 UTC, benediktahrens commented on TypeTheory/TypeConstructions/CwF_Structure_Display.v
> +Local Notation "Γ .: A" :=  (ext Γ A) (at level 24).
Please add a type annotation.

2021-05-29 17:18 UTC, benediktahrens commented on TypeTheory/TypeConstructions/CwF_Structure_Display.v
> +Definition pr1_tm {Γ : C} {A : Ty Γ : hSet} (a : tm A) := pr1 a.
Please add a type annotation.

2021-05-29 17:18 UTC, benediktahrens commented on TypeTheory/TypeConstructions/CwF_Structure_Display.v
> +  pathsinv0, (toforallpaths _ _ _ (pr22 pp _ _ f) a) .
Could you rework this proof to use several separate `apply` statements?

2021-05-29 17:18 UTC, benediktahrens commented on TypeTheory/TypeConstructions/CwF_Structure_Display.v
> +Defined.
How about defining this one as `invweq` of the one before? Would that compute less well?

2021-05-29 17:18 UTC, benediktahrens commented on TypeTheory/TypeConstructions/CwF_Structure_Display.v
> +(e' : A' = A'') (a : tm A) : tm_transportf (e @ e') a = tm_transportf e' (tm_transportf e a).
It is useful if the type annotation starts at the beginning of a line, like in the other definitions you give.

2021-05-29 17:18 UTC, benediktahrens commented on TypeTheory/TypeConstructions/CwF_Structure_Display.v
> +: _ ⟦Yo (_ .: (#Ty f A)), Yo (Γ.: A) ⟧.
Please fill in the details, instead of using underscore. You can copy them from Coq, of course.

2021-05-29 17:18 UTC, benediktahrens commented on TypeTheory/TypeConstructions/CwF_Structure_Display.v
> +: _ ⟦ _ .: (#Ty f A) , Γ.: A⟧.
Please fill in the details, instead of using underscore. You can copy them from Coq, of course.

2021-05-29 17:18 UTC, benediktahrens commented on TypeTheory/TypeConstructions/CwF_Structure_Display.v
> +:γ (te A) ;; #Yo (qq_term A (pi A)) ;; #Yo (pi A) = identity _;;(#Yo (pi A)).
space after colon

2021-05-29 17:18 UTC, benediktahrens commented on TypeTheory/TypeConstructions/CwF_Structure_Display.v
> +(a : tm A) : (Ty Γ : hSet) := ( γ a;;yy B : nat_trans _ _) Γ (identity Γ).
Please add type annotation.

2021-05-29 17:18 UTC, benediktahrens commented on TypeTheory/TypeConstructions/CwF_Structure_Display.v
> +:= (γ a;;yy b : nat_trans _ _) Γ (identity Γ).
Please add type annotation.

2021-05-29 17:18 UTC, benediktahrens commented on TypeTheory/TypeConstructions/CwF_Structure_Display.v
> +(b : tm B) (a : tm A) : tm (DepTypesType B a) := DepTypesElem_pr1 b a ,, DepTypesComp b a.
Start type annotation in new line.

2021-05-29 17:18 UTC, benediktahrens commented on TypeTheory/TypeConstructions/CwF_Structure_Display.v
> +(a b : tm A) (e : pr1 a = pr1 b) : DepTypesType B a = DepTypesType B b.
type annotation in new line

2021-05-29 17:18 UTC, benediktahrens commented on TypeTheory/TypeConstructions/CwF_Structure_Display.v
> +(Λ : CwF_PiAbs π) (app : CwF_PiApp π) : UU.
It is not great to define a type interactively. Can you copy the created type into the definition?

2021-05-29 17:18 UTC, benediktahrens commented on TypeTheory/TypeConstructions/CwF_Structure_Display.v
> +(pair : CwF_SigAbs σ) : UU.
Don't define types interactively, at least not in the final version - instead copy the type expression once you have created it using tactics.

2021-05-29 17:42 UTC, tvignon commented on TypeTheory/TypeConstructions/CwF_Structure_Display.v
> +Local Notation "Γ .: A" :=  (ext Γ A) (at level 24).
I'm sorry, I don't see where I forgot a type annotation in those line.

2021-05-29 17:51 UTC, benediktahrens commented on TypeTheory/TypeConstructions/CwF_Structure_Display.v
> +Local Notation "Γ .: A" :=  (ext Γ A) (at level 24).
Oups, I think I marked the wrong line. Sorry for that. Please ignore my comment.

2021-06-10 19:49 UTC, benediktahrens commented
@tvignon : please add your identity types, and then we can merge this PR.

2021-06-16 12:26 UTC, merged